/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication17;

import java.awt.Color;
import java.util.Random;

/**
 *
 * @author 3K FOR KIDS
 */
public class NewJFrame extends javax.swing.JFrame {


        Random random = new Random();

        int pcColor1 = random.nextInt(3) + 1 ;
        int pcColor2 = random.nextInt(3) + 1 ;       // Losowanie liczby z przedziału 1-3
        int pcColor3 = random.nextInt(3) + 1 ;

        int color = 1;
        int color2 = 1;
         int color3 =1 ;//  color  =2  = czerwony / color = 3 = niebieski / color = 1 = zółty /
         
         int color4 = 1;
         int color5 = 1 ;
         int color6 = 1;
         
         int color7 = 1;
         int color8 = 1;
         int color9 = 1;
         
         int color10 =1 ;
         int color11 = 1 ;
         int color12 = 1 ;
        
        
        int zabezpieczenie = 0;
        int position = 0 ;
        int position1 = 0 ;
        int position2 = 0 ;
        int position3 = 0 ;
        int position4 = 0 ;
        int position5 = 0 ;
        int position6 = 0 ;
        int position7 = 0;
        int position8 = 0; 
        
        int position9=0;
        int position10=0;
        int position11=0;
        
        
        int trafioneKolory = 0 ;
        int koloryNaSwoimMiejscu = 0 ;
        int a  = 0 ;
        int b = 0 ;
        int c = 0 ;
        int d = 0;
        int e = 0 ;
        int f = 0 ;
        int g = 0 ;
        int h = 0 ;
        int i = 0 ;
        int j = 0 ;
        int k = 0 ;
        int l = 0 ;
        
       
    


    
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MASTER MIND ");
        setBackground(new java.awt.Color(51, 255, 51));
        setFont(new java.awt.Font("AR BONNIE", 0, 14)); // NOI18N
        setForeground(java.awt.Color.black);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 0, 51)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(102, 0, 204), new java.awt.Color(0, 153, 51), new java.awt.Color(204, 0, 51), new java.awt.Color(102, 255, 102))));
        jPanel1.setForeground(new java.awt.Color(204, 0, 102));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Cambria Math", 0, 11)); // NOI18N

        jButton1.setBackground(java.awt.Color.lightGray);
        jButton1.setForeground(java.awt.Color.white);
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBorder(new javax.swing.border.MatteBorder(null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setText("Sprawdź!");
        jButton4.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createTitledBorder("")));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("AR CENA", 0, 18)); // NOI18N
        jLabel1.setText("Ustaw kolory , nastepnie wcisnij \"sprawdz!\" POWODZENIA!");

        jLabel3.setFont(new java.awt.Font("AR BLANCA", 0, 14)); // NOI18N
        jLabel3.setText("Próba nr : 0");

        jButton5.setBorder(new javax.swing.border.MatteBorder(null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBorder(new javax.swing.border.MatteBorder(null));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBorder(new javax.swing.border.MatteBorder(null));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Sprawdź!");
        jButton8.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createTitledBorder("")));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        jLabel6.setFont(new java.awt.Font("AR CARTER", 0, 36)); // NOI18N
        jLabel6.setText("MASTER MIND");

        jLabel4.setFont(new java.awt.Font("Urdu Typesetting", 0, 14)); // NOI18N
        jLabel4.setText("By Daniel Stolarski");

        jButton9.setText("Sprawdź!");
        jButton9.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createTitledBorder("")));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 255, 0));
        jLabel5.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 0));

        jButton10.setBorder(new javax.swing.border.MatteBorder(null));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBorder(new javax.swing.border.MatteBorder(null));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBorder(new javax.swing.border.MatteBorder(null));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBorder(new javax.swing.border.MatteBorder(null));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBorder(new javax.swing.border.MatteBorder(null));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBorder(new javax.swing.border.MatteBorder(null));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("Sprawdź!");
        jButton16.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createTitledBorder("")));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButton14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton16)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton4))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton8)))))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton9)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton16)))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        
        position2 = 1 ;
        if (a == 0 )
        {

            jButton3.setBackground(Color.red);
            a= 1 ;
            
            color3 = 2 ;
           
            }
              
        

        else if ( a ==1 ){

            jButton3.setBackground(Color.blue);
            a= 2 ;
            color3 = 3 ;

        }

        else if (a == 2 ){

            jButton3.setBackground(Color.yellow);
            color=1;
             a = 0 ;
           

        }
        
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

           
            position = 1 ;
            if (b  == 0 )
            {
                jButton1.setBackground(Color.red);
                color = 2;
                b = 1 ;
            }
            

            else  if ( b == 1  )
            {

                jButton1.setBackground(Color.blue);
                color = 3 ;
                b = 2 ;
            }
             

            else if ( b == 2 )
            {

                jButton1.setBackground(Color.yellow);
                color=1;
                
              
               b = 0 ;
            }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        
        position1 = 1 ;
            if (c  == 0 ) 
            {
                jButton2.setBackground(Color.red);
                color2 = 2;
                c = 1 ;
             }
            

            else  if ( c == 1  )
            {

                jButton2.setBackground(Color.blue);
                color2 = 3 ;
                c = 2 ;

             }
             

            else if ( c == 2 )
            {

                jButton2.setBackground(Color.yellow);
                color2=1;
                
           
                c = 0 ;

             }
      

        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
   
         
          jLabel3.setText("Próba nr : 1");
        if ( position == 1 && position1 == 1 && position2 == 1 )  //wszystkie przyciski musza byc klikniete zeby sprawdzic 
        {
            if ( color == pcColor1 || color2 == pcColor2 || color3== pcColor3){
                jLabel1.setText("Jeden kolor jest  na swoim miejscu ! ");
                if ( color== pcColor1 && color2 == pcColor2){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                    if ( color == pcColor1 && color2 == pcColor2 && color3 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                         jLabel5.setText("WYGRALES!!!");
                    }
                }
                if ( color == pcColor1 && color3 == pcColor3 ){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                     if ( color == pcColor1 && color2 == pcColor2 && color3 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                         jLabel5.setText("WYGRALES!!!");
                    }
                }
                if (color2 == pcColor2 && color3== pcColor3){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                     if ( color == pcColor1 && color2 == pcColor2 && color3 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                         jLabel5.setText("WYGRALES!!!");
                    }
                }
                
            } else {
                jLabel1.setText("Zaden kolor nie jest na swoim miejscu !");
            }
          
        }
          
         zabezpieczenie = 1 ;
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      if ( zabezpieczenie == 1 ){
             
            position4 = 1 ;
            if (d  == 0 )
            {
                jButton5.setBackground(Color.red);
                color4 = 2;
                d = 1 ;
            }
            

            else  if ( d == 1  )
            {

                jButton5.setBackground(Color.blue);
                color4 = 3 ;
                d = 2 ;
            }
             

            else if ( d == 2 )
            {

                jButton5.setBackground(Color.yellow);
                color4 =1;
                
              
               d = 0 ;
            }
      
          
          
          
      }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      
           
          jLabel3.setText("Próba nr : 2");
        if ( position3 == 1 && position4 == 1 && position5 == 1 )  //wszystkie przyciski musza byc klikniete zeby sprawdzic 
        {
            if ( color4 == pcColor1 || color5 == pcColor2 || color6== pcColor3){
                jLabel1.setText("Jeden kolor jest  na swoim miejscu ! ");
                if ( color4== pcColor1 && color5 == pcColor2){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                    if ( color4 == pcColor1 && color5 == pcColor2 && color6 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                        jLabel5.setText("WYGRALES!!!");
                    }
                }
                if ( color4 == pcColor1 && color6 == pcColor3 ){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                     if ( color4 == pcColor1 && color5 == pcColor2 && color6 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                           jLabel5.setText("WYGRALES!!!");
                    }
                }
                if (color5 == pcColor2 && color6== pcColor3){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                     if ( color4 == pcColor1 && color5 == pcColor2 && color6 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                         jLabel5.setText("WYGRALES!!!");
                    }
                }
                
            } else {
                jLabel1.setText("Zaden kolor nie jest na swoim miejscu !");
            }
          
          
        }
           zabezpieczenie = 2 ;
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if ( zabezpieczenie == 1 ) {
            
               
            position3 = 1 ;
            if (e  == 0 )
            {
                jButton6.setBackground(Color.red);
                color5 = 2;
                e = 1 ;
            }
            

            else  if ( e == 1  )
            {

                jButton6.setBackground(Color.blue);
                color5 = 3 ;
                e = 2 ;
            }
             

            else if ( e == 2 )
            {

                jButton6.setBackground(Color.yellow);
                color5 =1;
                
              
               e = 0 ;
            }
      
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
      if ( zabezpieczenie ==1 ) {
          
             
            position5 = 1 ;
            if (f  == 0 )
            {
                jButton7.setBackground(Color.red);
                color6 = 2;
                f = 1 ;
            }
            

            else  if ( f == 1  )
            {

                jButton7.setBackground(Color.blue);
                color6 = 3 ;
                f = 2 ;
            }
             

            else if ( f == 2 )
            {

                jButton7.setBackground(Color.yellow);
                color6=1;
                
              
              f = 0 ;
            }
      
      }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
           
         
          jLabel3.setText("Próba nr : 3");
          
        if ( position6 == 1 && position7 == 1 && position8 == 1 )  //wszystkie przyciski musza byc klikniete zeby sprawdzic 
        {
            if ( color7 == pcColor1 || color8 == pcColor2 || color9== pcColor3){
                jLabel1.setText("Jeden kolor jest  na swoim miejscu ! ");
                if ( color7== pcColor1 && color8 == pcColor2){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                    if ( color7 == pcColor1 && color8 == pcColor2 && color9 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                        jLabel5.setText("WYGRALES!!!");
                    }
                }
                if ( color7 == pcColor1 && color9 == pcColor3 ){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                     if ( color7 == pcColor1 && color8 == pcColor2 && color9 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                           jLabel5.setText("WYGRALES!!!");
                    }
                }
                if (color8 == pcColor2 && color9== pcColor3){
                    jLabel1.setText("Dwa kolory sa na swoim miejscu ! ");
                     if ( color7 == pcColor1 && color8 == pcColor2 && color9 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                         jLabel5.setText("WYGRALES!!!");
                    }
                }
                
            } else {
                jLabel1.setText("Zaden kolor nie jest na swoim miejscu !");
            }
           
        }
        zabezpieczenie = 3 ;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
             if ( zabezpieczenie == 2 ) {
            
               
            position7 = 1 ;
            if (h  == 0 )
            {
                jButton11.setBackground(Color.red);
                color8 = 2;
                h = 1 ;
            }
            

            else  if ( h == 1  )
            {

                jButton11.setBackground(Color.blue);
                color8 = 3 ;
                h = 2 ;
            }
             

            else if ( h == 2 )
            {

                jButton11.setBackground(Color.yellow);
                color8 =1;
                
              
               h = 0 ;
            }
      
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
     if ( zabezpieczenie == 2 ) {
            
               
            position8 = 1 ;
            if (i  == 0 )
            {
                jButton12.setBackground(Color.red);
                color9 = 2;
                i = 1 ;
            }
            

            else  if ( i == 1  )
            {

                jButton12.setBackground(Color.blue);
                color9 = 3 ;
                i = 2 ;
            }
             

            else if ( i == 2 )
            {

                jButton12.setBackground(Color.yellow);
                color9 =1;
                
              
               i = 0 ;
            }
      
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 if ( zabezpieczenie == 2 ){
             
            position6 = 1 ;
            if (g  == 0 )
            {
                jButton10.setBackground(Color.red);
                color7 = 2;
                g = 1 ;
            }
            

            else  if ( g == 1  )
            {

                jButton10.setBackground(Color.blue);
                color7 = 3 ;
                g = 2 ;
            }
             

            else if ( g == 2 )
            {

                jButton10.setBackground(Color.yellow);
                color7 =1;
                
              
               g = 0 ;
            }
      
          
          
          
      }       
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
       if ( zabezpieczenie == 3 ) {
            
               
            position9 = 1 ;
            if (j  == 0 )
            {
                jButton13.setBackground(Color.red);
                color10 = 2;
                j = 1 ;
            }
            

            else  if ( j == 1  )
            {

                jButton13.setBackground(Color.blue);
                color10 = 3 ;
                j = 2 ;
            }
             

            else if ( j == 2 )
            {

                jButton13.setBackground(Color.yellow);
                color10 =1;
                
              
               j = 0 ;
            }
      
        }     
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
      if ( zabezpieczenie == 3 ) {
            
               
            position10 = 1 ;
            if (k  == 0 )
            {
                jButton14.setBackground(Color.red);
                color11 = 2;
                k = 1 ;
            }
            

            else  if ( k == 1  )
            {

                jButton14.setBackground(Color.blue);
                color11 = 3 ;
                k = 2 ;
            }
             

            else if ( k == 2 )
            {

                jButton14.setBackground(Color.yellow);
                color11 =1;
                
              
               k = 0 ;
            }
      
        }     
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        if ( zabezpieczenie == 3 ) {
            
               
            position11 = 1 ;
            if (l  == 0 )
            {
                jButton15.setBackground(Color.red);
                color12 = 2;
                l = 1 ;
            }
            

            else  if ( l == 1  )
            {

                jButton15.setBackground(Color.blue);
                color12 = 3 ;
                l = 2 ;
            }
             

            else if ( l == 2 )
            {

                jButton15.setBackground(Color.yellow);
                color12 =1;
                
              
               l = 0 ;
            }
      
        }     
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
              
         
          jLabel3.setText("Próba nr : 4");
          
        if ( position6 == 1 && position7 == 1 && position8 == 1 )  //wszystkie przyciski musza byc klikniete zeby sprawdzic 
        {
            if ( color10 == pcColor1 || color11 == pcColor2 || color12== pcColor3){
                  jLabel1.setText("Przykro mi :( to byla twoja ostatnia szansa.!");
                jLabel5.setBackground(Color.RED);
                jLabel5.setText(" GAME OVER  ");
                if ( color10== pcColor1 && color11 == pcColor2){
                      jLabel1.setText("Przykro mi :( to byla twoja ostatnia szansa.!");
                jLabel5.setBackground(Color.RED);
                jLabel5.setText(" GAME OVER  ");
                    if ( color10 == pcColor1 && color11 == pcColor2 && color12 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                        jLabel5.setText("WYGRALES!!!");
                    }
                }
                if ( color10 == pcColor1 && color12 == pcColor3 ){
                      jLabel1.setText("Przykro mi :( to byla twoja ostatnia szansa.!");
                jLabel5.setBackground(Color.RED);
                jLabel5.setText(" GAME OVER  ");
                     if ( color10 == pcColor1 && color11 == pcColor2 && color12 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                           jLabel5.setText("WYGRALES!!!");
                    }
                }
                if (color11 == pcColor2 && color12== pcColor3){
                    
                       jLabel1.setText("Przykro mi :( to byla twoja ostatnia szansa.!");
                jLabel5.setBackground(Color.RED);
                jLabel5.setText(" GAME OVER  ");
                     if ( color10 == pcColor1 && color11 == pcColor2 && color12 == pcColor3 ){
                        jLabel1.setText("Wszystkie kolory sa na swoim miejscu !");
                         jLabel5.setText("WYGRALES!!!");
                    }
                }
                
            } else {
                jLabel1.setText("Przykro mi :( to byla twoja ostatnia szansa.!");
                jLabel5.setBackground(Color.RED);
                jLabel5.setText(" GAME OVER  ");
            }
           
        }
        zabezpieczenie = 4 ;
                                          

    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
